# Note this will only work with Release-Please if you have given it a PAT.
# The default GITHUB_TOKEN does not have permission to run workflows on releases
name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5

      - name: Setup DotNet âœ¨
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Install dependencies ğŸ“¦ï¸
        run: dotnet restore

      - name: Build ğŸ”¨
        run: dotnet build --no-restore -c Release

      # If not using <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      - name: Pack NuGet ğŸ—ï¸
        run: |
          dotnet pack --no-build -v normal --include-symbols -o nupkg

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{secrets.NUGET_USER}}

      - name: Push NuGet ğŸš€
        run: |
          dotnet nuget push **/*.nupkg -k ${{steps.login.outputs.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
